name: Purge jsDelivr cache

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        title: main
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@5.1.1
