name: Purge jsDelivr cache

on:
  push:
    branches:
      - "main"

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a Release
        uses: List-KR/semver-release@2.2.0
    needs: [eslint]
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@6.0.0
    needs: [eslint, release]
