name: Purge jsDelivr cache

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a Release
        uses: List-KR/semver-release@1.0.0
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@5.1.1
    needs: release
